### PR TITLE
New UI and settings

### PR DESCRIPTION
**Pull request by nashant**
Mostly changes based around UI.

Adds MiniCSS for css and AlpineJS as a minimal javascript framework, new devices and settings pages.
New settings format to allow for this and easy extension to settings, migrations from old settings format included.
Allow adding of unlimited devices.

### CODE REVIEW

**Comment by nashant** [comment]
Hold up, not quite ready I've realised

**Comment by nashant** [comment]
Ok, _now_ it's ready

**Comment by HeimdallMidgard** [comment]
Hey nashant. I tried to build your fork but when I connect the core is panic'ing and the ESP32 restarts. Andriensis also added some bugfixes so I created branch 0.2 so we can work there together on the next version. What I could see from the new design and changes it looks really awesome. Thanks for adding it.

**Comment by nashant** [comment]
I think I might be leaking memory somewhere. When reading pointers from the
json doc the data is corrupted and the memory addresses are, I think,
fairly close to the end of the address space. I think. But again, this is
the first c++ I've ever touched.

**Comment by HeimdallMidgard** [comment]
Issue was the delay. I increased the delay time. Issue is gone now.
I also changed some little things after reading your code updates. I would like to work in 0.2 branch and close this pull request so we can work together on it. Is this okay for you?

**Comment by nashant** [comment]
Absolutely, sounds like a great idea. I found increasing the interval and window sorted things out. I think that by the time the devices were being processed they had already been replaced in the scan (with duplicates set to be filtered out).

Just done another large push splitting things out and having a better way of initialising settings. Still need to sort out migration of devices a bit more.

**Comment by HeimdallMidgard** [comment]
Tbh I don't think this needs migration. Settings can just be done new. I don't think so many ppl are using this right now. Main problem I see at the moment is that the scanner doesn't work (didnt check your update right now). Can you please push updates inside the 0.2 than I don't need to do this handy. Thanks.

**Comment by nashant** [comment]
I've re-targeted to 0.2, feel free to merge into 0.2 and test

**Comment by nashant** [comment]
Adding the telemetry has been useful. Using a global `mqtt_msg` is leaking memory. It takes ~20mins for the heap to drop to ~50k free. I've switched it to using a local scoped char instead and the heap is holding strong at ~150k. Need to solve the problem of reporting to the webpage though, I'm thinking maybe an async websocket

**Comment by nashant** [comment]
Currently `{ "results_last_scan": "3", "free_heap": "147216", "uptime": "29243" }`

**Comment by nashant** [comment]
Websocket done

**Comment by andriensis** [comment]
settings.json doesn't seem to contain **bluetooth** key for bluetooth settings (scan_time, scan_interval)

**Comment by nashant** [comment]
Doesn't need to. If you check all the `initSettingsBlah` functions you'll see how they get created. In fact you don't need `settings.json` or `devices.json` at all, they'll both get initialised on first boot. Also means that one doesn't need to re-flash the data if new settings are added

**Comment by HeimdallMidgard** [comment]
At the moment the scanner function is broken. Core is panicing.

**Pull request merged**
